server:
  port: ${PORT:8080}

info:
  project:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    artifact-id: @project.artifactId@

spring:
  application:
    name: spring-boot-redis-cache
  cloud:
    config:
      name: spring-boot-redis-cache
  webflux:
    base-path: /party/customer-profile/v1



