spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_redis_cache?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging.level:
  com.example.springboot.rediscache: DEBUG

